"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY',default='test')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG',cast=bool,default=True)

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'multi_captcha_admin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'captcha',
    # 'django_summernote',
    'robots',
    'debug_toolbar',
    # 'taggit',
    'compressor',
    'django_extensions',
    'website.apps.WebsiteConfig',
    'blog',
    'accounts',
]

# site framework
SITE_ID = 2

# robots
ROBOTS_USE_HOST=True
ROBOTS_USE_SITEMAP=True

#summernote configs
UMMERNOTE_THEME='bs4'
SUMMERNOTE_CONFIG = {
    # Using SummernoteWidget - iframe mode, default
    'iframe': True,

    # You can put custom Summernote settings
    'summernote': {
        # As an example, using Summernote Air-mode
        'airMode': False,

        # Change editor size
        'width': '100%',
        'height': '480',

       

        # Toolbar customization
        # https://summernote.org/deep-dive/#custom-toolbar-popover
        'toolbar': [
            ['style', ['style']],
            ['font', ['bold', 'underline', 'clear']],
            ['fontname', ['fontname']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['table', ['table']],
            ['insert', ['link', 'picture', 'video']],
            ['view', ['fullscreen', 'codeview', 'help']],
        ],
    }
}

STATICFILES_FINDERS = [
    
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
]



COMPRESS_ENABLED = True
COMPRESS_OFFLINE = True
COMPRESS_CSS_FILTERS = [
    'compressor.filters.css_default.CssAbsoluteFilter',
    'compressor.filters.cssmin.CSSMinFilter',
]
COMPRESS_JS_FILTERS = [
    'compressor.filters.jsmin.JSMinFilter',
]


# captcha admin setting

MULTI_CAPTCHA_ADMIN = {
    'engine': 'simple-captcha',
}



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

if DEBUG:
    DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
else:
    DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE',default='django.db.backends.postgresql'),
        'NAME': config('DB_NAME',default='postgres'),
        'USER':config('DB_USER',default='postgres'),
        'PASSWORD':config('DB_PASS',default='postgres'),
        'HOST':config('DB_HOST',default='127.0.0.1'),
        'PORT':config('DB_PORT',cast=int,default=5432),
    }
}
    





# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATIC_ROOT=BASE_DIR/'static'
MEDIA_ROOT=BASE_DIR/'media'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]
MEDIAFILES_DIRS = [
    BASE_DIR / "media",
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

INTERNAL_IPS = [
   '127.0.0.1',
]





LOGIN_REDIRECT_URL='/'
#EMAIL SETTING

if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = config('EMAIL_BACKEND',default='django.core.mail.backends.smtp.EmailBackend')
    EMAIL_HOST = config('EMAIL_HOST',default='smtp.gmail.com')
    EMAIL_PORT = config('EMAIL_PORT',default=587)
    EMAIL_HOST_USER = config('EMAIL_HOST_USER',default='sayeshalmashi50@gmail.com') #your email-id
    EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD',default='jlxf tucj fpeb ueja') #your password
    EMAIL_USE_TLS = config('EMAIL_USE_TLS',cast=bool,default=True)
    EMAIL_USE_SSL = config('EMAIL_USE_SSL',cast=bool,default=False)

#security config for production
if config("USE_SSL_SETTINGS",cast=bool,default=False):
    # HTTPS SETTING
    SESSION_COOKIE_SECURE=True
    CSRF_COOKIE_SECURE=True
    SECURE_SSL_REDIRECT=True

    # HSTS SETTINGS
    SECURE_HSTS_SECONDS= 31536000 #1year
    SECURE_HSTS_PRELOAD= True
    SECURE_HSTS_INCLUDE_SUBDOMAINS= True

    #more security settings
    SECURE_CONTENT_TYPE_NOSNIFF= True
    SECURE_BROWSER_XSS_FILTER=True
    X_FRAME_OPTIONS='SAMEORIGIN'  #baraye load frame ha az jahaye dg mesl frame summernote  
    SECURE_REFERRER_POLICY='strict-origin'
    USE_X_FORWARDED_HOST=True
    SECURE_PROXY_SSL_HEADER=('HTTP_X_FORWARDED_PROTO', 'https')